#define THORVG_VERSION_STRING "1.0.7"
#define THORVG_CPU_ENGINE_SUPPORT
#define THORVG_SVG_LOADER_SUPPORT
//#define THORVG_PNG_LOADER_SUPPORT
//#define THORVG_JPG_LOADER_SUPPORT
//#define THORVG_WEBP_LOADER_SUPPORT
#define THORVG_LOTTIE_LOADER_SUPPORT
#define THORVG_THREAD_SUPPORT
#define THORVG_FILE_IO_SUPPORT
#if defined(__ARM_NEON__) || defined(__aarch64__)
#define THORVG_NEON_VECTOR_SUPPORT
#else
//#define THORVG_AVX_VECTOR_SUPPORT
#endif
